#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <errno.h>
#include <arpa/inet.h>
#include <signal.h>
#include <math.h>
#define MAXIMUM_LINES 1000
#define MAX_LISTEN_Q 10

// stores connected clients ip in this after fork.
char clientname[MAXIMUM_LINES];

// MESSAGE STRUCT FOR COMMUNICATION
typedef struct Message {
	int type_id;
	char msg[MAXIMUM_LINES];
} Message;

// RETURNS THE DESIRED MESSAGE IN THE ARRAY
char* message_to_char(Message m){
	char *opt = (char*) malloc((1+MAXIMUM_LINES)*sizeof(char));
	opt[0] = (char) ((int) '0' + m.type_id);
	int i;
	strcpy(opt+1, m.msg);
	return opt;
}

// RETURNS THE DESIRED MESSAGE IN STRUCT FORMAT
Message* char_to_message(char* input){
	Message* opt = (Message*) malloc(sizeof(Message));
	strcpy(opt->msg, input + 1);
	opt->type_id = (int) (input[0] - '0');
	return opt;
}

/* converts a char array to an int array by converting each byte to its binary representation and storing this in an int array. Also it adds 0 padding so that total no of bits are divisible by 6.
blen = length of returned int array
len = length of base64 encoded msg generated by encoding msg.

ex. msg = "ABC";
returns array = {1,0,0,0,0,0,1,1,0,0,0,0,1,0,1,0,0,0,0,1,1}
blen = 21
len = 4
*/
int *char_to_bits(char *msg, int *len, int *blen){
	int n = strlen(msg);
	int sz = n*8;
	if(sz%6)
		sz += (6 -sz%6);
	*len = sz/6;
	if(n%3==1)
		(*len)+=2;
	if(n%3==2)
		(*len)+=1;
	*blen = sz;
	int *bits = (int *)malloc(sz*sizeof(int));
	int idx = 0,i,j;
	for(i = 0;i < n;i++){
		int p  = (int)msg[i];
		for(j=0;j<8;j++){
			bits[idx + 7-j] = (p%2);
			p/=2;
		}
		idx += 8;
	}
	for(i=idx;i<sz;i++)
		bits[i] = 0;
	return bits;
}

// returns corresponding char for each int in base64 encoding.
char mapchar(int i){
    if(i < 26)
        return 'A' + i;
    else if(i < 52)
        return 'a' + i -26;
    else if(i < 62)
        return '0' + i - 52;
    else
        return (i == 62)? '+':'/';
}

char binary_to_char(int *bits, int s,int e){
	int p = 0,i;
	for(i=e;i>=s;i--)
		p = p + bits[i]*(1 << e-i);
	return mapchar(p);
}
/**
 - encodes character array data to base64 encoded format
 - returns the encoded data in the original array thus modifying it
 **/
void encode(char*data){
	int f,i,j;
	int n = strlen(data);
	char msg[MAXIMUM_LINES];
	strcpy(msg, data);

	for(i=0;i<strlen(data);i++){
		if(data[i] == '\r' || data[i] == '\n' || data[i] == '\0'){
			f = i;
			break;
		}
	}
	msg[f] = '\0';

	int encoded_len, bits_len;
	int *bits = char_to_bits(msg, &encoded_len, &bits_len);
	char *encoded_msg = (char*) malloc((encoded_len+n-f+1)*sizeof(char));
	for(i=0;i<bits_len/6;i++)
		encoded_msg[i] = binary_to_char(bits, i*6, i*6 + 5);
	for(i=bits_len/6;i<encoded_len;i++)
		encoded_msg[i] = '=';
	encoded_msg[encoded_len] = '\0';
	int p = encoded_len;
    for(i=p;i<p+(n-f+1);i++)
		encoded_msg[i] = data[f + i-p];
	strcpy(data, encoded_msg);
    free(encoded_msg);
	free(bits);
}
// converts decimal to binary numbers and returns the binary reprsentation in char array temp[i].
void decimalToBinary_d(long n, char temp[][6], int I ) {
    int remainder;
    int j = 5;
    while(n!=0) {
        remainder = n%2;
        n = n/2;
		if(remainder == 0)		temp[I][j] = '0';
		else					temp[I][j] = '1';
		j--;
    }

    int i;
    for(i=0;i<=j;i++)
	temp[I][i] = '0';

}
// converts a binary array representing an int to its decimal form and return it as int.
int binaryToDecimal_d(char *t ) {
    int decimal = 0, i = 0;
    while (i<8) {
        if(t[7-i] == '1')
        	decimal +=(int) (1 << i);
        ++i;
    }
    return decimal;

}
/**
	- makes another copy of the message which contains the whole message except '\r', '\n', '\0'
	- evaluates the length of the original message by the considering the number of '=' appended
	- translates the encoded binary data into decimal format
	- appends the special characters ('\r' and '\n', '\0') after encoding the content
 **/
void decode(char *msg){
	char EncodedMessage[100000];
	int f,x;
	for(x=0;x<strlen(msg);x++){
		if(msg[x] == '\r' || msg[x] == '\n' || msg[x] == '\0'){
			f = x;
			break;
		}
	}

	for(x=0;x<f;x++)
		EncodedMessage[x] = msg[x];
	EncodedMessage[f] = '\0';
	int len = strlen(EncodedMessage);
	int sub = 0;
	int alen = len;
	if(EncodedMessage[len-1] == '='){
		if(EncodedMessage[len-2] == '='){
			alen = len-2;
			sub = 4;
		}
		else{
			alen = len-1;
			sub = 2;
		}
	}
	alen = (alen*6 - sub)/8;

    char code[64] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

	int i,j;
	char temp[100000][6];
	char tempf[600000];

	// bzero(tempf, sizeof(char)*600000);

	for(i=0;i<strlen(EncodedMessage);i++)
		for(j=0;j<=63;j++)
			if(EncodedMessage[i]==code[j])
			{
				decimalToBinary_d(j,temp,i);
				break;
			}

	int remai = strlen(EncodedMessage) * 6  - strlen(temp[0]);

	if(remai == 6)
	{
		int i;
		for(i=0;i<strlen(temp[0])-2;i++) // removed two 0
			tempf[i] = temp[0][i];
	}
	else if(remai == 12)
	{
		int i;
		for(i=0;i<strlen(temp[0])-4;i++)  // removed four 0
			tempf[i] = temp[0][i];
	}
	else
	{
		int i;
		for(i=0;i<strlen(temp[0]);i++)
			tempf[i] = temp[0][i];
	}


	char DecodedMessage[100000];
	int k = 0;

	int flag = strlen(tempf) / 8;
	int a = flag;
	while(flag)
	{
		char x[8];
		int j;
		for(j=0;j<8;j++)
		    x[j] = tempf[(a-flag)*8 + j];

		DecodedMessage[k++] = (char) binaryToDecimal_d(x);
		flag--;
	}

	DecodedMessage[alen] = '\0';

	int p = strlen(DecodedMessage);
	int n = strlen(msg);
	for(x=p;x<p+(n-f+1);x++)
		DecodedMessage[x] = msg[f + x-p];
	strcpy(msg, DecodedMessage);
	for(i=0;i< 100000;i++)
		DecodedMessage[i] = '\0';
	for(i=0;i< 600000;i++)
		tempf[i] = '\0';
}

// store parents pid before forking.
pid_t pid_parent;
/* Write "n" bytes to a descriptor. */
ssize_t
write_the_data(int fd, const void *vptr, size_t n)
{
    size_t              nleft;
    ssize_t             nwritten;
    const char  *ptr;
    ptr = (char *)vptr;
    nleft = n;
    while (nleft > 0) {
        if ( (nwritten = write(fd, ptr, nleft)) <= 0) {
            if (errno == EINTR)
                nwritten = 0;           /* and call write() again */
            else
                return(-1);             /* error */
        }

        nleft -= nwritten;
        ptr   += nwritten;
    }
    return(n);
}
// handles writen errors
void Writen(int fd, void *ptr, size_t nbytes){
    if (write_the_data(fd, ptr, nbytes) != nbytes)
        perror("writen error");
}
// returns true if M starts with "close"
bool isClose(char *M){
	if(strlen(M) < 5)
		return false;
	if(M[0] != 'c')
		return false;
	if(M[1] != 'l')
		return false;
	if(M[2] != 'o')
		return false;
	if(M[3] != 's')
		return false;
	if(M[4] != 'e')
		return false;
	return true;
}

typedef struct sockaddr SA;
/**
 - waits for message of client
 - receives the message from client and creates the "Message" object(message) from the received character array(buf)
 - displays client ID, MESSAGE_ID
 - decodes the content the "Message" object
 - creates another "Message" object(smessage) corresponding to "ACK" and store its message type ID and
   content into smessage object
 - translates the message object into character array and sends it to client
**/
void server_func(int sockfd){
	ssize_t n;
	char buf[MAXIMUM_LINES];
	bzero(buf, MAXIMUM_LINES*sizeof(char));

	again:
		while((n = read(sockfd, buf, MAXIMUM_LINES)) > 0){
			Message* m = char_to_message(buf);
			printf("Message received from client %s:\n", clientname);
			printf("Type_id: %d\nmessage: %s\n\n",m->type_id, m->msg);
			printf("Encoded message:%s",m->msg);

			decode(m->msg);
			bool is_close = isClose(m->msg);
			printf("Decoded message:%s",m->msg);
			free(m);

			Message sm;
			sm.type_id = 2;
			snprintf(sm.msg, sizeof(sm.msg),"ACK\r\n");
			encode(sm.msg);

			char *m_com = message_to_char(sm);
			Writen(sockfd, m_com, strlen(m_com));
			free(m_com);
			bzero(buf, sizeof(buf));

			if(is_close){
				printf("client sent close.\n");
				printf("closing socket....\n");
				close(sockfd);
				exit(1);                                                                       // check close server.
			}
		}
		if(n < 0){
			goto again;
		}
}


// returns true if s is an integer
bool is_int(char *s){
	int i;
	for(i=0;i<strlen(s);i++){
		if(s[i] < '0' || s[i] > '9')
			return false;
	}
	return true;
}

int L_socket,C_socket;

/**
 used if ctrl-C is pressed to send close signal to client to terminate the servers process serving this client
 and close open sockets ie release socket resources.
**/
void signalHandler(int signalValue){
	printf("sending close to clients...\n");

	char sendline[MAXIMUM_LINES];

	bzero(sendline, sizeof(sendline));
	snprintf(sendline, sizeof(sendline), "close\r\n");
	encode(sendline);

	Message m;
	m.type_id = 3;
	strcpy(m.msg, sendline);
	char* m_com = message_to_char(m);

	if(getpid() != pid_parent)
		Writen(C_socket, m_com, strlen(m_com));
	free(m_com);

	if(getpid() == pid_parent)
		printf("closing sockets....\n");
	close(L_socket);

	if(getpid() == pid_parent)
		printf("exiting...\n");
	exit(0);
}


int main(int argc, char **argv){
	pid_parent = getpid();
	signal(SIGINT, signalHandler);

	//checking for errors
	if(argc != 2){
		printf("usage: <executable> <port>\n");
		exit(1);
	}

	if(!is_int(argv[1])){
		printf("port must be an unsigned integer\n");
		exit(1);
	}

	int serv_port = atoi(argv[1]);

	// invalid port
	if(serv_port < 0 || serv_port > 65535){
		printf("port number must be between 0 and 65535.\n");
		exit(1);
	}

	int listen_socket, conn_socket;
	pid_t pid_child;
	socklen_t cli_len;
	struct sockaddr_in cli_addr, serv_addr;

	printf("Creating socket...\n");
	listen_socket = socket(AF_INET, SOCK_STREAM, 0);
	printf("socket created!\n");
	L_socket = listen_socket;
	bzero(&serv_addr, sizeof(serv_addr)); //inserting null values to all fields of the struct

	serv_addr.sin_family = AF_INET;
	serv_addr.sin_addr.s_addr = htonl(INADDR_ANY); //localhost IP address
	serv_addr.sin_port = htons(serv_port);

	bind(listen_socket, (SA *) &serv_addr, sizeof(serv_addr));

	listen(listen_socket, MAX_LISTEN_Q);
	printf("listening at port %d\n", serv_port);

	for( ; ; ){
		cli_len = sizeof(cli_addr);
		conn_socket = accept(listen_socket, (SA *) &cli_addr, &cli_len);
		char client[100];
		inet_ntop(AF_INET, &cli_addr.sin_addr, client, 100);
		printf("client %s connected\n", client);
		strcpy(clientname, client);
		if((pid_child = fork()) == 0 ){
			C_socket = conn_socket;
			close(listen_socket);
			server_func(conn_socket);
			exit(0);
		}

		if(getpid() == pid_parent)
			close(conn_socket);
	}
	return 0;
}
